import { Actividad, DiaSemana, EstadoActividad, Moneda } from "../models";

export const actividades: Actividad[] = [
  {
    id: "act-1",
    nombre: "Escuela de Natación Delfines",
    descripcion: "Clases de natación para niños con instructores certificados. Piscina semiolímpica climatizada, grupos reducidos por nivel.",
    categoriaId: "cat-1",
    rangoEdadId: "edad-1",
    zonaId: "zona-2",
    esGratuita: false,
    precioDesde: 150000,
    precioHasta: 250000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9995,
    longitud: -74.8109,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.MARTES, horaInicio: "15:00", horaFin: "16:00" },
      { diaSemana: DiaSemana.JUEVES, horaInicio: "15:00", horaFin: "16:00" },
      { diaSemana: DiaSemana.SABADO, horaInicio: "09:00", horaFin: "10:00" },
    ],
    contacto: { telefono: "605-3601234", whatsapp: "3001234567", email: "info@delfinsbaq.com", direccion: "Cra 53 #79-120, Villa Country", sitioWeb: null, instagram: "@delfines_baq" },
    creadoEn: "2026-01-15T10:00:00Z",
    actualizadoEn: "2026-01-15T10:00:00Z",
  },
  {
    id: "act-2",
    nombre: "Taller de Pintura Creativa",
    descripcion: "Taller donde los niños exploran técnicas de acuarela, acrílico y mixtas. Materiales incluidos. Exposición final cada trimestre.",
    categoriaId: "cat-2",
    rangoEdadId: "edad-2",
    zonaId: "zona-1",
    esGratuita: false,
    precioDesde: 80000,
    precioHasta: 120000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9837,
    longitud: -74.7889,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "14:00", horaFin: "16:00" },
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "14:00", horaFin: "16:00" },
    ],
    contacto: { telefono: null, whatsapp: "3109876543", email: "tallercreativo@gmail.com", direccion: "Calle 53 #46-40, Prado", sitioWeb: null, instagram: "@tallercreativo_baq" },
    creadoEn: "2026-01-20T10:00:00Z",
    actualizadoEn: "2026-01-20T10:00:00Z",
  },
  {
    id: "act-3",
    nombre: "Academia de Fútbol Tiburones",
    descripcion: "Formación deportiva integral en fútbol. Entrenadores con licencia, torneos internos mensuales y participación en ligas infantiles.",
    categoriaId: "cat-1",
    rangoEdadId: "edad-2",
    zonaId: "zona-3",
    esGratuita: false,
    precioDesde: 100000,
    precioHasta: 180000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9762,
    longitud: -74.7950,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "16:00", horaFin: "17:30" },
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "16:00", horaFin: "17:30" },
      { diaSemana: DiaSemana.VIERNES, horaInicio: "16:00", horaFin: "17:30" },
    ],
    contacto: { telefono: "605-3785432", whatsapp: "3205551234", email: null, direccion: "Cancha El Recreo, Cra 21 #45-10", sitioWeb: null, instagram: "@tiburones_fc" },
    creadoEn: "2026-02-01T10:00:00Z",
    actualizadoEn: "2026-02-01T10:00:00Z",
  },
  {
    id: "act-4",
    nombre: "Robótica para Niños — TechKids",
    descripcion: "Introducción a la robótica con kits LEGO Education y Arduino básico. Proyectos prácticos cada mes. Competencias regionales.",
    categoriaId: "cat-4",
    rangoEdadId: "edad-3",
    zonaId: "zona-2",
    esGratuita: false,
    precioDesde: 200000,
    precioHasta: 300000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 11.0042,
    longitud: -74.8145,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.SABADO, horaInicio: "09:00", horaFin: "11:00" },
    ],
    contacto: { telefono: null, whatsapp: "3151112233", email: "techkids@outlook.com", direccion: "Cra 51B #82-254, Local 3, Buenavista", sitioWeb: "https://techkidsbaq.com", instagram: "@techkids_baq" },
    creadoEn: "2026-02-10T10:00:00Z",
    actualizadoEn: "2026-02-10T10:00:00Z",
  },
  {
    id: "act-5",
    nombre: "Clases de Guitarra Infantil",
    descripcion: "Aprende guitarra desde cero con método lúdico. Clases individuales y grupales. Recital semestral para padres.",
    categoriaId: "cat-3",
    rangoEdadId: "edad-2",
    zonaId: "zona-1",
    esGratuita: false,
    precioDesde: 120000,
    precioHasta: 180000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9918,
    longitud: -74.7862,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.MARTES, horaInicio: "16:00", horaFin: "17:00" },
      { diaSemana: DiaSemana.JUEVES, horaInicio: "16:00", horaFin: "17:00" },
    ],
    contacto: { telefono: "605-3401122", whatsapp: "3187654321", email: null, direccion: "Calle 72 #41-67, Bellavista", sitioWeb: null, instagram: "@guitarra_kids_baq" },
    creadoEn: "2026-02-15T10:00:00Z",
    actualizadoEn: "2026-02-15T10:00:00Z",
  },
  {
    id: "act-6",
    nombre: "Ballet Clásico — Estudio Arabesque",
    descripcion: "Formación en ballet clásico con metodología Vaganova. Presentaciones en el Teatro Amira de la Rosa.",
    categoriaId: "cat-6",
    rangoEdadId: "edad-1",
    zonaId: "zona-2",
    esGratuita: false,
    precioDesde: 180000,
    precioHasta: 250000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9945,
    longitud: -74.8056,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "15:00", horaFin: "16:30" },
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "15:00", horaFin: "16:30" },
      { diaSemana: DiaSemana.SABADO, horaInicio: "10:00", horaFin: "11:30" },
    ],
    contacto: { telefono: null, whatsapp: "3004567890", email: "arabesque.baq@gmail.com", direccion: "Cra 54 #70-45, Altos del Limón", sitioWeb: null, instagram: "@arabesque_baq" },
    creadoEn: "2026-02-20T10:00:00Z",
    actualizadoEn: "2026-02-20T10:00:00Z",
  },
  {
    id: "act-7",
    nombre: "Inglés para Niños — Little Explorers",
    descripcion: "Programa de inmersión en inglés con metodología comunicativa. Grupos por nivel, máximo 8 niños. Certificación Cambridge YLE.",
    categoriaId: "cat-5",
    rangoEdadId: "edad-1",
    zonaId: "zona-2",
    esGratuita: false,
    precioDesde: 250000,
    precioHasta: 350000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 11.0068,
    longitud: -74.8118,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "14:00", horaFin: "15:30" },
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "14:00", horaFin: "15:30" },
      { diaSemana: DiaSemana.VIERNES, horaInicio: "14:00", horaFin: "15:30" },
    ],
    contacto: { telefono: "605-3856789", whatsapp: "3162345678", email: "info@littleexplorers.co", direccion: "Calle 84 #51-30, Villa Country", sitioWeb: "https://littleexplorers.co", instagram: "@littleexplorers_baq" },
    creadoEn: "2026-03-01T10:00:00Z",
    actualizadoEn: "2026-03-01T10:00:00Z",
  },
  {
    id: "act-8",
    nombre: "Taller de Cerámica y Modelado",
    descripcion: "Los niños aprenden a modelar con arcilla y cerámica en frío. Desarrolla motricidad fina y creatividad. Piezas para llevar a casa.",
    categoriaId: "cat-2",
    rangoEdadId: "edad-3",
    zonaId: "zona-1",
    esGratuita: false,
    precioDesde: 90000,
    precioHasta: 130000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9685,
    longitud: -74.7813,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.SABADO, horaInicio: "10:00", horaFin: "12:00" },
    ],
    contacto: { telefono: null, whatsapp: "3123456789", email: "ceramicakids@gmail.com", direccion: "Calle 45 #44-12, Centro", sitioWeb: null, instagram: "@ceramica_kids" },
    creadoEn: "2026-03-05T10:00:00Z",
    actualizadoEn: "2026-03-05T10:00:00Z",
  },
  {
    id: "act-9",
    nombre: "Patinaje Artístico — Club Ruedas",
    descripcion: "Clases de patinaje artístico y recreativo. Préstamo de patines para principiantes. Exhibiciones en el Parque Venezuela.",
    categoriaId: "cat-1",
    rangoEdadId: "edad-2",
    zonaId: "zona-1",
    esGratuita: false,
    precioDesde: 80000,
    precioHasta: 140000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9803,
    longitud: -74.7911,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.MARTES, horaInicio: "17:00", horaFin: "18:30" },
      { diaSemana: DiaSemana.JUEVES, horaInicio: "17:00", horaFin: "18:30" },
      { diaSemana: DiaSemana.SABADO, horaInicio: "08:00", horaFin: "09:30" },
    ],
    contacto: { telefono: "605-3691234", whatsapp: "3198765432", email: null, direccion: "Parque Venezuela, entrada norte", sitioWeb: null, instagram: "@clubruedas_baq" },
    creadoEn: "2026-03-10T10:00:00Z",
    actualizadoEn: "2026-03-10T10:00:00Z",
  },
  {
    id: "act-10",
    nombre: "Programación con Scratch",
    descripcion: "Introducción a la programación visual con Scratch. Los niños crean sus propios juegos y animaciones. Sin experiencia previa.",
    categoriaId: "cat-4",
    rangoEdadId: "edad-2",
    zonaId: "zona-3",
    esGratuita: true,
    precioDesde: null,
    precioHasta: null,
    moneda: null,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9710,
    longitud: -74.7830,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.SABADO, horaInicio: "14:00", horaFin: "16:00" },
    ],
    contacto: { telefono: null, whatsapp: "3176543210", email: "scratch.baq@gmail.com", direccion: "Biblioteca Piloto del Caribe, Cra 45 #36-35", sitioWeb: null, instagram: "@scratch_baq" },
    creadoEn: "2026-03-15T10:00:00Z",
    actualizadoEn: "2026-03-15T10:00:00Z",
  },
  {
    id: "act-11",
    nombre: "Danza Urbana — Street Kids",
    descripcion: "Hip hop, breaking y dancehall para niños y adolescentes. Coreografías grupales, batallas amistosas y shows en eventos locales.",
    categoriaId: "cat-6",
    rangoEdadId: "edad-3",
    zonaId: "zona-3",
    esGratuita: false,
    precioDesde: 70000,
    precioHasta: 120000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9730,
    longitud: -74.7980,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.MARTES, horaInicio: "17:00", horaFin: "18:30" },
      { diaSemana: DiaSemana.JUEVES, horaInicio: "17:00", horaFin: "18:30" },
    ],
    contacto: { telefono: null, whatsapp: "3014567890", email: null, direccion: "Casa de la Cultura, Calle 40 #27-15, Modelo", sitioWeb: null, instagram: "@streetkids_baq" },
    creadoEn: "2026-03-20T10:00:00Z",
    actualizadoEn: "2026-03-20T10:00:00Z",
  },
  {
    id: "act-12",
    nombre: "Coro Infantil Voces del Caribe",
    descripcion: "Formación vocal para niños. Repertorio variado: folclor, pop y clásico. Presentaciones en eventos culturales de la ciudad.",
    categoriaId: "cat-3",
    rangoEdadId: "edad-3",
    zonaId: "zona-1",
    esGratuita: true,
    precioDesde: null,
    precioHasta: null,
    moneda: null,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9856,
    longitud: -74.7953,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "15:00", horaFin: "17:00" },
      { diaSemana: DiaSemana.SABADO, horaInicio: "10:00", horaFin: "12:00" },
    ],
    contacto: { telefono: "605-3401567", whatsapp: null, email: "vocesdelcaribe@gmail.com", direccion: "Teatro Amira de la Rosa, Cra 54 #52-106", sitioWeb: null, instagram: "@vocesdelcaribe" },
    creadoEn: "2026-04-01T10:00:00Z",
    actualizadoEn: "2026-04-01T10:00:00Z",
  },
  {
    id: "act-13",
    nombre: "Taekwondo Infantil — Tigres Dorados",
    descripcion: "Arte marcial coreano para niños. Disciplina, defensa personal y competencia. Exámenes de cinturón cada 3 meses.",
    categoriaId: "cat-1",
    rangoEdadId: "edad-2",
    zonaId: "zona-4",
    esGratuita: false,
    precioDesde: 90000,
    precioHasta: 150000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9185,
    longitud: -74.7680,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "17:00", horaFin: "18:30" },
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "17:00", horaFin: "18:30" },
      { diaSemana: DiaSemana.VIERNES, horaInicio: "17:00", horaFin: "18:30" },
    ],
    contacto: { telefono: "605-3741234", whatsapp: "3221234567", email: null, direccion: "Coliseo de Soledad, Cra 20 #15-30", sitioWeb: null, instagram: "@tigresdorados_tkd" },
    creadoEn: "2026-04-05T10:00:00Z",
    actualizadoEn: "2026-04-05T10:00:00Z",
  },
  {
    id: "act-14",
    nombre: "Experimentos Científicos — Lab Kids",
    descripcion: "Laboratorio de ciencias para niños curiosos. Experimentos de química, física y biología adaptados. Bata y gafas incluidas.",
    categoriaId: "cat-4",
    rangoEdadId: "edad-2",
    zonaId: "zona-2",
    esGratuita: false,
    precioDesde: 130000,
    precioHasta: 200000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9960,
    longitud: -74.8070,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.SABADO, horaInicio: "10:00", horaFin: "12:00" },
      { diaSemana: DiaSemana.DOMINGO, horaInicio: "10:00", horaFin: "12:00" },
    ],
    contacto: { telefono: null, whatsapp: "3134567890", email: "labkids.baq@gmail.com", direccion: "Cra 52 #76-120, Local 5, Altos del Limón", sitioWeb: null, instagram: "@labkids_baq" },
    creadoEn: "2026-04-10T10:00:00Z",
    actualizadoEn: "2026-04-10T10:00:00Z",
  },
  {
    id: "act-15",
    nombre: "Francés para Niños — Petit Monde",
    descripcion: "Clases de francés con enfoque comunicativo y cultural. Juegos, canciones y actividades inmersivas. Alianza con Alliance Française.",
    categoriaId: "cat-5",
    rangoEdadId: "edad-3",
    zonaId: "zona-2",
    esGratuita: false,
    precioDesde: 200000,
    precioHasta: 280000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 11.0010,
    longitud: -74.8098,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.MARTES, horaInicio: "15:00", horaFin: "16:30" },
      { diaSemana: DiaSemana.JUEVES, horaInicio: "15:00", horaFin: "16:30" },
    ],
    contacto: { telefono: "605-3856700", whatsapp: "3167890123", email: "petitmonde@gmail.com", direccion: "Calle 80 #53-15, Villa Country", sitioWeb: null, instagram: "@petitmonde_baq" },
    creadoEn: "2026-04-15T10:00:00Z",
    actualizadoEn: "2026-04-15T10:00:00Z",
  },
  {
    id: "act-16",
    nombre: "Cumbia y Folclor Infantil",
    descripcion: "Aprende los ritmos del Caribe colombiano: cumbia, mapalé y puya. Vestuario para presentaciones incluido.",
    categoriaId: "cat-6",
    rangoEdadId: "edad-2",
    zonaId: "zona-5",
    esGratuita: true,
    precioDesde: null,
    precioHasta: null,
    moneda: null,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9550,
    longitud: -74.7720,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.VIERNES, horaInicio: "16:00", horaFin: "18:00" },
      { diaSemana: DiaSemana.SABADO, horaInicio: "09:00", horaFin: "11:00" },
    ],
    contacto: { telefono: "605-3551234", whatsapp: "3041234567", email: null, direccion: "Casa de la Cultura de Barlovento, Calle 17 #21-45", sitioWeb: null, instagram: "@folclor_infantil_baq" },
    creadoEn: "2026-04-20T10:00:00Z",
    actualizadoEn: "2026-04-20T10:00:00Z",
  },
  {
    id: "act-17",
    nombre: "Ajedrez Estratégico — Peones del Caribe",
    descripcion: "Clases de ajedrez para desarrollar pensamiento lógico y concentración. Torneos internos y participación en campeonatos departamentales.",
    categoriaId: "cat-4",
    rangoEdadId: "edad-3",
    zonaId: "zona-1",
    esGratuita: false,
    precioDesde: 60000,
    precioHasta: 100000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9700,
    longitud: -74.7840,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "16:00", horaFin: "17:30" },
      { diaSemana: DiaSemana.MIERCOLES, horaInicio: "16:00", horaFin: "17:30" },
    ],
    contacto: { telefono: null, whatsapp: "3189012345", email: "peonesdelcaribe@gmail.com", direccion: "Biblioteca Departamental, Calle 36 #44-100", sitioWeb: null, instagram: "@peones_caribe" },
    creadoEn: "2026-05-01T10:00:00Z",
    actualizadoEn: "2026-05-01T10:00:00Z",
  },
  {
    id: "act-18",
    nombre: "Teatro Infantil — Pequeños Actores",
    descripcion: "Taller de teatro y expresión escénica. Improvisación, trabajo en equipo y montaje de obra final. Función abierta al público.",
    categoriaId: "cat-2",
    rangoEdadId: "edad-3",
    zonaId: "zona-1",
    esGratuita: false,
    precioDesde: 100000,
    precioHasta: 160000,
    moneda: Moneda.COP,
    estado: EstadoActividad.PUBLICADA,
    imagenUrl: null,
    latitud: 10.9780,
    longitud: -74.7880,
    proveedorId: null,
    cuposDisponibles: 20,
    destacada: false,
    horarios: [
      { diaSemana: DiaSemana.LUNES, horaInicio: "15:00", horaFin: "17:00" },
      { diaSemana: DiaSemana.VIERNES, horaInicio: "15:00", horaFin: "17:00" },
    ],
    contacto: { telefono: "605-3401890", whatsapp: "3156789012", email: "pequenosactores@hotmail.com", direccion: "Teatro Municipal, Cra 43 #50-16", sitioWeb: null, instagram: "@pequenosactores_baq" },
    creadoEn: "2026-05-05T10:00:00Z",
    actualizadoEn: "2026-05-05T10:00:00Z",
  },
];
